### ISSUE TITLE
Add support for Clarabel solver

### ISSUE THREAD

**Issue by bstellato** [cvxgrp/diffcp#60]
It would be great to add support for [Clarabel solver](https://github.com/oxfordcontrol/Clarabel.rs). Since it is already supported in cvxpy, and it takes very similar inputs as SCS, I believe it should not be difficult. 

What do you think? @bamos @goulart-paul @PTNobel

**Comment by goulart-paul** [comment]
Is the suggestion here to use the Clarabel solver through its python interface or through C++?   If the latter, note that we have just released a C++ interface with Eigen compatibility [here](https://github.com/oxfordcontrol/Clarabel.cpp).

**Comment by bstellato** [comment]
I was suggesting to use the Python interface. For reference, see how SCS gets called [here](https://github.com/cvxgrp/diffcp/blob/f43449683c5cddef9a8e05d9c45b6ad66ab619f6/diffcp/cone_program.py#L256). I think it should be quite easy to add Clarabel as an option. (I suspect the quadratic objectives still don't work in diffcp, but it would already be very helpful to have an interior-point SDP solver here).

**Comment by sbarratt** [comment]
https://github.com/cvxgrp/diffcp/pull/61/files
